// SPDX-FileCopyrightText: 2026 Frederic Ruget <fred@atlant.is> (GitHub: @douzebis)
//
// SPDX-License-Identifier: MIT

//! The `F1` help overlay's text.
//!
//! Its own file because it is prose, not code: 180 lines of it with no
//! logic to read it against, which used to sit between the enums above
//! it and the `App` struct below. `tests/help_text.rs` is what keeps it
//! honest.

/// Static key-binding reference shown by the `F1` help overlay (spec 0111
/// Annex C, spec 0113 D22) — kept as one flat text block rather than
/// generated from the `handle_key` match arms, so it can be phrased for
/// readability independent of the code's own binding order.
pub(super) const HELP_TEXT: &[&str] = &[
    "protolens — key bindings",
    "",
    "Movement — the text first, then on past its edges into the tree",
    "  h / Left / Backspace",
    "                   caret one character left; at the first non-blank,",
    "                   fold this node, then move to its parent",
    "  l / Right        caret one character right; at the first non-blank",
    "                   of a folded node, unfold it; at the last",
    "                   reachable column, move to the first child",
    "  Alt-Left / Alt-h caret one word left",
    "  Alt-Right / Alt-l  caret one word right",
    "  0 / ^ / Ctrl-A   caret to first non-blank",
    "  $ / Ctrl-E       caret to last reachable column",
    "  %                jump between the cursor node's { and }",
    "  j / Down / Ctrl-N  next node (document order)",
    "  k / Up / Ctrl-P  previous node",
    "  J / Shift-Down   next sibling",
    "  K / Shift-Up     previous sibling",
    "  Home / gg        jump to first node",
    "  End / G          jump to last visible node",
    "  Space / Ctrl-F / PageDown",
    "                   scroll down one page",
    "  Shift-Space / Ctrl-B / PageUp",
    "                   scroll up one page — Shift-Space needs terminal",
    "                   support for modifier reporting, Ctrl-B always works",
    "  Ctrl-Left        pan main pane left",
    "  Ctrl-Right       pan main pane right",
    "  Ctrl-Up          pan main pane up, cursor stays in view",
    "  Ctrl-Down        pan main pane down, cursor stays in view",
    "  Shift+wheel / native horizontal scroll",
    "                   pan whichever pane (main, override, manage, or",
    "                   the command bar) the mouse is hovering",
    "  drag (main pane) select whole lines; release copies them to the",
    "                   OS clipboard; Esc clears the selection",
    "",
    "Fold / unfold",
    "  z                toggle fold on the node under the cursor",
    "  Z                the same, and force every descendant into the",
    "                   state the node itself just took",
    "  H / Shift-Left   fold all siblings at this level",
    "  L / Shift-Right  unfold all siblings at this level",
    "  click on a fold marker",
    "                   toggle that node and put the cursor on it",
    "",
    "Display",
    "  a                toggle main-pane #@ annotation display",
    "  w                toggle wire mode — under every drawn line, a",
    "                   second row showing that line's own bytes in hex",
    "",
    "Navigation history",
    "  Ctrl-O           jump back",
    "  Ctrl-I           jump forward",
    "",
    "Export",
    "  x                arm the export chord — xb/xp pre-fill \":export\"",
    "                   for binary/prototext data; xd arms a second",
    "                   chord — xdb/xdp pre-fill \":export\" for binary/",
    "                   prototext schema",
    "  :export [--binary|--prototext|--descriptor-binary|",
    "           --descriptor-prototext] <path>",
    "                   export the cursor node to <path> — default",
    "                   format is #@ prototext text; --descriptor-binary/",
    "                   --descriptor-prototext export a synthetic schema",
    "                   for the cursor's live-tree children instead of",
    "                   its data",
    "",
    "Command line",
    "  :                open the command line — works from any pane, so",
    "                   every command below is reachable without first",
    "                   returning focus to the main pane",
    "  Tab              complete the command name (longest common prefix,",
    "                   then cycle through matches)",
    "  Shift-Tab        cycle backward through matches",
    "  Ctrl-B / Ctrl-F  caret one character left / right",
    "  Alt-B / Alt-F    caret one word left / right",
    "  Left / Right     caret one character left / right",
    "  Alt-Left / Alt-Right  caret one word left / right",
    "  Esc              discard the command line",
    "  :quit            quit",
    "  :proto-root <dir>",
    "                   set the root the v key resolves .proto sources",
    "                   against, overriding --proto-root for this session",
    "",
    "Search (main pane, requires main-pane focus)",
    "  /                search forward for a pattern (matches against the",
    "                   current, possibly-overridden rendering)",
    "  ?                search backward",
    "  n                repeat the last search, same direction",
    "  N                repeat the last search, opposite direction",
    "  (a hit puts the caret on the match itself)",
    "  (confirming / or ? with no typed pattern reuses the last one)",
    "",
    "Override pane",
    "  t                open/close the override pane for the message/",
    "                   group node under the cursor",
    "  Tab              move focus between the main pane and the",
    "                   override pane (while it is open)",
    "  i                toggle candidate sort: inferred score (default)",
    "                   or alphanumeric",
    "  /  ?  n  N       search / search backward / repeat / repeat",
    "                   opposite direction (pane focused)",
    "  j/k or Ctrl-N/Ctrl-P, PageUp/Down, Home/End",
    "                   move the highlighted candidate",
    "                   (pane focused)",
    "  Ctrl-Left/Ctrl-Right         pan the pane horizontally",
    "  Ctrl-Up/Ctrl-Down            pan the pane vertically, highlight",
    "                   stays in view",
    "  Enter            apply the highlighted type (pane focused) and",
    "                   close the pane; also records the override in the",
    "                   collection (see \"Override management\" below)",
    "  Esc              cancel and close the override pane",
    "  :type-as <FQDN>  apply <FQDN> as the cursor node's type override,",
    "                   bypassing the pane",
    "  :type-as-raw     mark the cursor node's range as explicitly raw/",
    "                   unschema'd, bypassing the pane",
    "",
    "Override management",
    "  o                open/close the override management pane (closes",
    "                   the override pane, if open)",
    "  Enter            close the management pane",
    "  Tab              move focus between the main pane and the",
    "                   management pane (while it is open)",
    "  j/k or Ctrl-N/Ctrl-P, PageUp/Down, Home/End",
    "                   move the highlighted entry",
    "  Shift-Up / Shift-Down        move the highlighted entry and",
    "                   activate the destination (deactivating any",
    "                   other entry sharing its origin)",
    "  Left/Right       move the main-pane cursor to the prev/next field",
    "                   affected by the highlighted entry (wraps around)",
    "  Ctrl-Left/Ctrl-Right         pan the pane horizontally",
    "  Ctrl-Up/Ctrl-Down            pan the pane vertically, highlight",
    "                   stays in view",
    "  /  ?  n  N       search / search backward / repeat / repeat",
    "                   opposite direction",
    "  a / Space        toggle the highlighted entry active/inactive",
    "  A / Shift-Space  same, but also cascades the new state to every",
    "                   entry whose origin sits at-or-under it (a",
    "                   descendant path, or a path-field/fqdn-field at",
    "                   the same path); when several entries would",
    "                   activate under one origin, only the first",
    "                   (sorted) one does — Shift-Space needs terminal",
    "                   support (Kitty keyboard protocol); also",
    "                   available as Shift-click or double-click on an",
    "                   entry's marker",
    "  z / Z            rotate the highlighted entry's origin kind",
    "                   forward/backward: path, path-field, fqdn-field;",
    "                   auto-resolves from the fields the entry affects,",
    "                   falling back to the main-pane cursor/message line",
    "                   when ambiguous; repeating z/Z with the cursor",
    "                   unchanged advances to the next kind instead of",
    "                   getting stuck",
    "  d / Delete / Backspace  remove the highlighted entry from the",
    "                   collection (an auto-derived entry still in scope",
    "                   is deactivated instead, since deleting it would",
    "                   just recreate it)",
    "  D                duplicate the highlighted entry (the copy starts",
    "                   inactive and is always manual, even if the",
    "                   original was auto-derived)",
    "  f                edit the highlighted entry's display-name",
    "                   override, pre-filled with its current value",
    "  entry rows: auto-derived entries are plain, manual entries bold",
    "  s                pre-fill \":save <default path>\"",
    "  r                pre-fill \":restore \"",
    "  :save <path>",
    "                   write the whole override collection to <path>",
    "                   as YAML",
    "  :restore <path>",
    "                   replace the override collection wholesale with",
    "                   <path>'s contents (entries that no longer",
    "                   resolve are silently dropped; a target-hash",
    "                   mismatch warns but does not block)",
    "  Tab              complete a filesystem path (save/restore",
    "                   argument)",
    "  (management-pane actions never change the current rendering —",
    "  only Enter in the override pane does)",
    "",
    "Other",
    "  v                open the FQDN under focus's .proto declaration in",
    "                   Neovim — works from any pane; needs a proto root",
    "                   (--proto-root or :proto-root) — Unix only",
    "  F1               toggle this help",
    "  q                quit (press again to confirm)",
    "  Ctrl-Z           suspend (fg to resume) — Unix only",
    "",
    "j/k, Ctrl-N/Ctrl-P or PageUp/PageDown scroll this help; q, Esc, or",
    "F1 closes it.",
];
